### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by smortezah** [burkhard-morgenstern/Slope-SpaM#3]
- I get the following error when trying to build the program:
```
CMake Error at CMakeLists.txt:10 (add_subdirectory):
  The source directory

    ***/Slope-SpaM/third_party/fmt

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
```

- By git cloning, the folder "third_party" remains empty.

**Comment by jschellh** [comment]
Did you use the '--recursive' flag when cloning? That should also clone the third_party repositories.

The README states to clone using:
'git clone --recursive https://github.com/burkhard-morgenstern/Slope-SpaM'

For me, that worked just fine.
